swagger: "2.0"
info:
  description: "Movies"
  version: "1.0.0"
  title: "Movies API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tva51g3smg.execute-api.us-east-1.amazonaws.com"
basePath: "/"
tags:
- name: "movies"
  description: "Everything about movies"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
paths:
  /movies/queryYear/{year}:
    get:
      tags:
      - "movies"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "year"
        type: integer
        description: "The year the movie was released"
        required: true
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/MoviesListing"
        "405":
          description: "Invalid input"
      x-amazon-apigateway-integration:
        uri: ${lambda_invoke_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
      x-amazon-apigateway-auth:
        type: "NONE"
  /movies/queryTitles:
    post:
      tags:
      - "movies"
      summary: "Place an order for a pet"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Search titles by year"
        required: true
        schema:
          $ref: "#/definitions/TitlesQuery"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/MoviesListing"
        "400":
          description: "Invalid Query"
      x-amazon-apigateway-integration:
        uri: ${lambda_invoke_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
      x-amazon-apigateway-auth:
        type: "NONE"
  /movie/getByTitle:
    post:
      tags:
      - "movies"
      summary: "Get by title"
      description: "Get a single movie by its title"
      operationId: "getByTitle"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Title of the movie"
        required: true
        schema:
          $ref: "#/definitions/SingleTitleGet"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Movie"
        "400":
          description: "Invalid Order"
      x-amazon-apigateway-integration:
        uri: ${lambda_invoke_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
      x-amazon-apigateway-auth:
        type: "NONE"
definitions:
  SingleTitleGet:
    type: "object"
    properties:
      title:
        type: "string"
  TitlesQuery:
    type: "object"
    properties:
      year:
        type: "integer"
        format: "int32"
      firstLetter:
        type: "string"
      lastLetter:
        type: "string"
  MoviesListing:
    type: "array"
    items:
      $ref: "#/definitions/Movie"
  Movie:
    type: "object"
    properties:
      year:
        type: "integer"
        format: "int32"
      title:
        type: "string"
      info:
        $ref: "#/definitions/Info"
  Info:
    type: "object"
    properties:
      directors:
        type: "array"
        items:
          type: "string"
      release_date: 
        type: "string"
      rating:
        type: "number"
      genres:
        type: "array"
        items:
          type: "string"
      image_url:
        type: "string"
      plot:
        type: "string"
      rank:
        type: "integer"
        format: "int32"
      running_time_secs:
        type: "integer"
        format: "int32"
      actors:
        type: "array"
        items:
          type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"